version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - llm
      - tts
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development

  llm:
    image: my-local-llm
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    restart: unless-stopped

  tts:
    image: coqui-ai/tts
    ports:
      - "9000:9000"
    volumes:
      - ./tts_models:/models
    command: tts-server --model_path /models/da_model.pth
    restart: unless-stopped 